spring.application.name=lv2-final-mission

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:database

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

#spring.sql.init.mode=never

spring.profiles.active=auth

spring.output.ansi.enabled=ALWAYS

email.connect-timeout-length=3s
email.read-timeout-length=5s

logging.level.org.springframework=debug
logging.level.org.springframework.web.client.RestClient=trace
logging.level.root=info
logging.file.name=logs/application.log
